[tool.poetry]
name = "home-assistant-spothinta"
version = "0.1.0"
description = "Custom component for Home Assistant for fetching energy spot prices for the Nordic and Baltic market."
authors = ["Sebastian Lövdahl <sebastian.lovdahl@hibox.fi>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "spothinta", from = "custom_components"}
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.10"
spothinta = "^0.1.1"

[tool.poetry.group.dev.dependencies]
homeassistant = ">=2023.5.0"
pytest-homeassistant-custom-component = ">=0.3.1"
black = "^22.12"
isort = "^5.12.0"

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = [
    "homeassistant",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true
